# Generated by Django 5.1.7 on 2025-04-02 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('expiration_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('Kat Steynberg', 'Kat Steynberg'), ('Other Provider', 'Other Provider')], max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('Incomplete', 'Incomplete'), ('In-Progress', 'In-Progress'), ('Complete', 'Complete')], default='Incomplete', max_length=20)),
                ('materials', models.JSONField(default=list)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohort_courses', to='lms_api.cohort')),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialization_cohorts', to='lms_api.cohort')),
                ('courses', models.ManyToManyField(blank=True, related_name='specialization_courses', to='lms_api.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_specializations', to='lms_api.specialization'),
        ),
        migrations.AddField(
            model_name='cohort',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='cohort_specializations', to='lms_api.specialization'),
        ),
        migrations.CreateModel(
            name='AdminAssignedCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_courses', to='lms_api.cohort')),
                ('courses', models.ManyToManyField(related_name='admin_assigned_courses', to='lms_api.course')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_specializations', to='lms_api.specialization')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('physical_address', models.TextField()),
                ('preferred_name', models.CharField(max_length=100, unique=True)),
                ('cohort', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='lms_api.cohort')),
                ('registered_courses', models.ManyToManyField(blank=True, related_name='registered_users', to='lms_api.course')),
                ('specialization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_specializations', to='lms_api.specialization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='specialization',
            name='registered_profiles',
            field=models.ManyToManyField(blank=True, related_name='specialization_profiles', to='lms_api.userprofile'),
        ),
    ]
